services:
  # 1. O BANCO DE DADOS LOCAL Notebook Fatec)
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_dados:/data/db

  # 2. O BACKEND (API)
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    # O Docker respeita  o que estiver no .env
    env_file:
      - ./backend/.env
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

  # 3. O FRONTEND (Interface)
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

# Define onde o banco de dados local vai salvar os arquivos no seu PC
volumes:
  mongo_dados:
