services:
  # 1. O BANCO DE DADOS
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_dados:/data/db

  # 2. O BACKEND (API)
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # O Docker vai criar essa variável de ambiente lá dentro do container
      - MONGO_URI=mongodb://db:27017/relatorio_estagios

    develop:
      # --- CONFIGURAÇÃO DO WATCH PARA A API ---
      watch:
        # Regra 1: Se mudar código, apenas sincronize (rápido)
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        # Regra 2: Se mudar as dependências, reconstrua tudo
        - action: rebuild
          path: ./backend/package.json

  # 3. O FRONTEND (Interface)
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    # --- CONFIGURAÇÃO DO WATCH PARA O REACT ---
    develop:
      watch:
        # Regra 1: Se mudar código, apenas sincronize (rápido)
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        # Regra 2: Se mudar as dependências, reconstrua tudo
        - action: rebuild
          path: ./frontend/package.json

# Configuração do "Disco Rígido" externo
volumes:
  mongo_dados:
